export const RESPONSE_MESSAGES = {
    INVALID_PARAMETER: 'Invalid/Missing parameters',
    RECIPE_FOUND: 'Successfully retrieved recipes',
    RECIPE_NOT_FOUND: 'Recipe not found.',
    INVALID_USER_ID: 'Invalid user id',
    USER_ALREADY_EXIST: 'User already exists !',
    INVALID_USER: 'Invalid user! Please Sign-Up',
    RECIPE_CREATED: 'Recipe Created successfully',
    USER_NOT_FOUND: 'User not found.',
    AUTH_RECIPE_DETAIL: 'Details include',
    INVALID_TOKEN: 'Invalid token.',
    TOKEN_REFRESHED: 'Token Refreshed',
    SUCCESSFUL_UPDATED: 'User updated successfully!',
    SIGNUP_SUCCESS: 'Sign-up successful! Redirecting to login page in 2 seconds...',
    LOGIN_SUCCESS: 'Login successful! Closing in 1 seconds...',
    SERVER_ERROR: 'Something went wrong, please try again later.',
    UNAUTHORIZED: 'Unauthorized user access.',
    BAD_REQUEST: 'Invalid request parameters.',
    FORBIDDEN: 'Access denied.',
    INVALID_CREDENTIALS: 'Invalid credentials. Please try again.',
}
